version: '3.8'
services:
  MyDB:
    container_name: authDB
    hostname: authDB
    image: postgres:alpine
    networks:
      - auth-network
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d authDB" ]

  auth:
    container_name: authService
    hostname: auth_service
    restart: always
    build: .
    image: astu/auth:v1
    environment:
      AUTH_DB_CONNECTION: jdbc:postgresql://authDB/authDB
      AUTH_DB_USER: admin
      AUTH_DB_PASSWORD: admin
    env_file:
      - .env
    depends_on:
      MyDB:
        condition: service_healthy
    networks:
      - services-network
      - auth-network

networks:
  auth-network:
    driver: bridge

  services-network:
    external:
      name: private-astu-services-network