version: '3.8'
services:
  MyDB:
    container_name: authDB
    image: postgres
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d authDB" ]
      interval: 1s

  auth:
    container_name: authService
    restart: always
    build: .
    image: astu/auth:v1
    environment:
      AUTH_DB_CONNECTION: jdbc:postgresql://authDB/authDB
      AUTH_DB_USER: admin
      AUTH_DB_PASSWORD: admin
    env_file:
      - .env
    ports:
      - "50000:50000"
      - "50001:50001"
    depends_on:
      MyDB:
        condition: service_healthy

